### ISSUE TITLE
What is in maven-settings.xml.gpg?

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkiverse-devops#101]
@gastaldi I'd like to setup a release workflow for one of my repo much like it is done in Quarkiverse. The only bit I am missing is the content of maven-settings.xml.gpg. Could you please share the template (without secrets) and some steps how to encrypt it?

**Comment by gastaldi** [comment]
@ppalaga is just has a `<server>` entry with the credentials to deploy to sonatype. 

Note that we no longer use it in newly generated projects, because the `actions/setup-java` workflow step already generates a settings.xml for us: https://github.com/quarkiverse/quarkus-prettytime/blob/main/.github/workflows/release.yml#L62

**Comment by ppalaga** [comment]
Thanks a lot @gastaldi! This is what I have now, and it works! https://github.com/l2x6/cq-maven-plugin/blob/main/.github/workflows/release.yml
